# Generated by Django 3.1.7 on 2021-03-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('caisse_id', models.AutoField(primary_key=True, serialize=False)),
                ('caisse_des', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie_des', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.AutoField(primary_key=True, serialize=False)),
                ('commande_num', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('emplacement_id', models.AutoField(primary_key=True, serialize=False)),
                ('emplacement_des', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_id', models.AutoField(primary_key=True, serialize=False)),
                ('prduit_nom', models.CharField(max_length=250)),
                ('produit_prix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_des', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nom', models.CharField(max_length=250)),
                ('user_pseudo', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('caisse_default', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('lignecommande_id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('diviser_par', models.CharField(max_length=250)),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood_app.commande')),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood_app.produit')),
            ],
        ),
    ]
